const data = [
    {
        id: 1,
        name: "Acetaminophen",
        description: "test",
        morning: false,
        afternoon: true,
        evening: false,
        select: "After",
        tablet: "0.5",
    },
    {
        id: 2,
        name: "Himalaya",
        description: "test",
        morning: true,
        afternoon: false,
        evening: true,
        select: "Before",
        tablet: "1 full",
    },
    {
        id: 3,
        name: "Jiwadaya",
        description: "test",
        morning: false,
        afternoon: true,
        evening: true,
        select: "After",
        tablet: "0.5",
    },
    {
        id: 4,
        name: "Humira",
        description: "test",
        morning: true,
        afternoon: true,
        evening: false,
        select: "Before",
        tablet: "0.5",
    },
    {
        id: 5,
        name: "Esticof",
        description: "test",
        morning: true,
        afternoon: false,
        evening: false,
        select: "Before",
        tablet: "1 full",
    },
    {
        id: 6,
        name: "Adderall",
        description: "test",
        morning: false,
        afternoon: true,
        evening: false,
        select: "After",
        tablet: "1 full",
    },

]
export default data;